services:
  simulator:
    image: ghcr.io/autowarefoundation/openadkit_demo.autoware:aws-reinvent-simulator-arm64
    network_mode: "host"
    restart: always
    volumes:
      - ./etc/simulation:/autoware/scenario-sim
    environment:
      - ROS_DOMAIN_ID=88
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - SIMULATION_OUTPUT_DIRECTORY=/autoware/result
    command: >
      ros2 launch scenario_test_runner scenario_test_runner.launch.py
      architecture_type:=awf/universe/20240605
      record:=false
      scenario:=/autoware/scenario-sim/scenario/yield_maneuver_demo.yaml
      sensor_model:=sample_sensor_kit
      vehicle_model:=sample_vehicle
      initialize_duration:=90
      global_timeout:=$TIMEOUT
      global_frame_rate:=20
      launch_autoware:=false
      launch_rviz:=false
      output_directory:=/autoware/result

  planning-control:
    image: ghcr.io/autowarefoundation/openadkit_demo.autoware:aws-reinvent-planning-control-arm64
    restart: always
    depends_on:
      - simulator 
    volumes:
      - ./etc/simulation/config:/autoware/config
      - ./etc/simulation/config/change_parameters:/usr/local/bin/change_parameters
      - ./etc/simulation:/autoware/scenario-sim
      - $CONF_FILE:/opt/autoware/share/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/static_obstacle_avoidance.param.yaml
      - $COMMON_FILE:/opt/autoware/share/autoware_launch/config/planning/scenario_planning/common/common.param.yaml
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=88
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - SIMULATION_ID=1
      - PLANNING_OUTPUT_FILE=/autoware/result/planning_result.txt
    command: >
      ros2 launch autoware_launch planning_simulator.launch.xml
      map_path:=/autoware/scenario-sim/map
      vehicle_model:=sample_vehicle
      sensor_model:=sample_sensor_kit
      scenario_simulation:=true
      rviz:=false
      perception/enable_traffic_light:=false

  web-visualizer:
    image: ghcr.io/autowarefoundation/demo_packages:simulator-visualizer-arm64
    container_name: web-visualizer
    network_mode: "host"
    restart: on-failure
    volumes:
      - ./etc/simulation:/autoware/scenario-sim
    environment:
      - ROS_DOMAIN_ID=88
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_URL=${NGROK_URL}
      - VNC_ENABLED=true
    command: >-
      sleep infinity

